config/routes.rb
Rails.application.routes.draw do
  get 'books/new'
  root to: 'homes#top'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  get 'top' => 'homes#top'
  post 'books' => 'books#create'
  get 'books' => 'books#index'
  get 'books/:id' => 'books#show', as: 'book'
  get 'books/:id/edit' => 'books#edit', as: 'edit_book'
  get 'books/:id/back' => 'books#back', as: 'back_book'
  patch 'books/:id' => 'books#update', as: 'update_book'
  delete 'books/:id' => 'books#destroy', as: 'destroy_book'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/book.rb
class Book < ApplicationRecord
	validates :title, presence: true
	validates :body, presence: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/books_controller.rb
class BooksController < ApplicationController
	def create
  	  @books = Book.all
  	  @book = Book.new(book_params)
  	  if @book.save
        flash[:notice] = "Book was successfully created."
        redirect_to book_path(@book.id)
  	  else
  	  	render 'index'
  	  end
  end

  def index
  	  @books = Book.all
      @book = Book.new
  end

  def show
  	  @book = Book.find(params[:id])
  end

  def edit
  	  @book = Book.find(params[:id])
  end

  def update
  	  @book = Book.find(params[:id])
  	  if @book.update(book_params)
  	  	flash[:notice] = "Book was successfully updated."
  	  	redirect_to book_path(@book.id)
  	  else
  	  	@books = Book.all
  	  	render 'edit'
  	  end
  end

  def destroy
  	  book = Book.find(params[:id])
  	  if book.destroy
  	  	flash[:notice] = "Book was successfully destroyed."
  	  	redirect_to books_path
  	  else
  	  	books = Book.all
  	    render 'index'
  	  end
  end
  private

  def book_params
  	  params.require(:book).permit(:title, :body)
  end
end

app/controllers/homes_controller.rb
class HomesController < ApplicationController
	def top
	end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/books_helper.rb
module BooksHelper
end

app/helpers/homes_helper.rb
module HomesHelper
end

app/views/books/edit.html.erb
<h2 id="/books">Editing Book</h2>
<%= form_for(@book, url:"/books/#{@book.id}") do |f| %>
  <% if @book.errors.any? %>
  <div id="error_explanation">
 	<h2><%= pluralize(@book.errors.count, "error") %> prohibited this book from being saved:</h2>
 	<ul>
 		<% @book.errors.full_messages.each do |msg| %>
 		  <li><%= msg %></li>
        <% end %>
    </ul>
  </div>
  <% end %>
	<h5>Title</h5>
	<%= f.text_field :title %>
	<h5>Body</h5>
	<%= f.text_area :body %>
	<%= f.submit 'Update Book' %>
<% end %>
<%= link_to "Show", book_path(@book.id) %>
<%= link_to "Back", books_path %>

app/views/books/index.html.erb
<% if flash[:notice] %>
	<%= flash[:notice] %>
<% end %>

<h2>Books</h2>
<table>
	<tbody>
			<% @books.each do |book| %>
	  			<tr>
	  				<td><%= book.title %></td>
	  				<td><%= book.body %></td>
	  				<td>
	  					<%= link_to "Show", book_path(book.id) %>
	  				</td>
	  				<td>
	  					<%= link_to "Edit", edit_book_path(book.id) %>
	  				</td>
	  				<td>
	  					<%= link_to "Destroy", book_path(book.id), method: :delete, "data-confirm" => "Are you sure？" %>
	  				</td>
	  			</tr>
  			<% end %>
  	</tbody>
</table>
<h2>New book</h2>
<%= form_for(@book, url: '/books') do |f| %>
<% if @book.errors.any? %>
  <div id="error_explanation">
 	<h2><%= pluralize(@book.errors.count, "error") %> prohibited this book from being saved:</h2>
 	<ul>
 		<% @book.errors.full_messages.each do |msg| %>
 		  <li><%= msg %></li>
        <% end %>
    </ul>
  </div>
  <% end %>

<h5>Title</h5>
<%= f.text_field :title %>

<h5>Body</h5>
<%= f.text_area :body %>

<%= f.submit 'Create Book' %>
<% end %>

app/views/books/show.html.erb
<% if flash[:notice] %>
	<%= flash[:notice] %>
<% end %>
<h5>Title:</h5>
<p><%= @book.title %></p>
<h5>Body:</h5>
<p><%= @book.body %></p>
<%= link_to "Edit", edit_book_path(@book.id) %>
<%= link_to "Back", books_path %>

app/views/homes/top.html.erb
    <h1>
  	  ようこそ <strong>Bookers</strong> へ！
  	</h1>
  	<p>
  	  <storng>Bookers</storng>では、さまざまな書籍に関するあなたの意見や
  	</p>
  	<p>印象を共有し交換することができます</p>
  	<p>
  	  <%= link_to "start", books_path %>
  	</p>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Bookers0</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>